### ISSUE TITLE
User Associations

### ISSUE THREAD

**Issue by sgreenstein** [sgreenstein/salk-a#2]
The User's associations need to be defined as outlined in the ER diagram: https://docs.google.com/drawings/d/12c1jAwVN3YhkWTx5SHF0QRDivrGab43kAaY27IhfHmI/edit
This page explains how: http://book.cakephp.org/2.0/en/models/associations-linking-models-together.html
This also means adding columns camper_id, site_id, and camp_id to the database

**Comment by zshall** [comment]
https://github.com/sgreenstein/salk-a/commit/f1b7a6b7bfec4c0dab0e4c849cfc6702be005608 - Finished.
